name: Deploy to Emsio Servers

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Emsio Docker Registry
        uses: docker/login-action@v3
        with:
          registry: registry.emsio.cz
          username: robot$${{ secrets.DEPLOY_REGISTRY_USER }}+ci
          password: ${{ secrets.DEPLOY_REGISTRY_PASSWORD }}

      - name: Build and Push Docker Image to Emsio Registry
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: .
          push: true
          #secrets: |
          #  PROP=VALUE
          #  PROP2=${{ secrets.SOMESECRET }}
          tags: |
            registry.emsio.cz/${{ secrets.DEPLOY_REGISTRY_USER }}/${{ secrets.PROJECT_UUID }}:latest

      - name: Deploy to Emsio
        uses: AldiiX/emsio-deploy@v4
        with:
          app_secret: ${{ secrets.APP_SECRET }}